import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import {
  LucideAngularModule,
  Home,
  User,
  Search,
  Mail,
  Phone,
  Building,
  KeyRound,
  Filter,
  QrCode,
  Edit,
  Trash2,
  AlertCircle,
  AlertTriangle,
  BarChart3,
  Menu,
  X,
  Copy,
  Download,
  Check,
  PlusIcon,
  CircleX,
  CircleCheckBig,
  LogOut,
  Settings,
  Shield,
  Eraser,
  Eye,
  EyeOff,
  Clock,
  CircleEllipsis,
  History,
  Inbox,
  Calendar,
  CloudUpload,
  Upload,
  Folder,
  FolderOpen,
  ArrowLeft,
  RotateCcw,
  FileText,
  LogOutIcon,
  Lock,
  Sun,
  Moon,
  Info,
  Bell,
  ChevronRight,
  RefreshCcw,
  Laptop,
  Monitor,
  ChevronDown,
  ChevronUp,
  Play,
  Trash,
  ChartBar,
  Database,
  TrendingUp,
  Image,
  Activity,
  File,
  Package,
  FilePlus,
  ExternalLink,
  Loader,
  Pause,
  HelpCircle,
  Shell,
} from 'lucide-angular';

@Component({
  selector: 'app-icon',
  imports: [LucideAngularModule],
  templateUrl: './icon.html',
  styleUrl: './icon.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Icon {
  name = input.required<string>();
  size = input<number>(24);
  class = input<string>('');

  private iconMap: Record<string, any> = {
    home: Home,
    user: User,
    search: Search,
    mail: Mail,
    phone: Phone,
    build: Building,
    key: KeyRound,
    filter: Filter,
    qr: QrCode,
    edit: Edit,
    trash: Trash2,
    alert: AlertCircle,
    'alert-triangle': AlertTriangle,
    chart: BarChart3,
    menu: Menu,
    close: X,
    copy: Copy,
    download: Download,
    check: Check,
    plus: PlusIcon,
    cancel: CircleX,
    ok: CircleCheckBig,
    logOut: LogOut,
    settings: Settings,
    shield: Shield,
    eraser: Eraser,
    eye: Eye,
    'eye-off': EyeOff,
    clock: Clock,
    more: CircleEllipsis,
    history: History,
    inbox: Inbox,
    calendar: Calendar,
    'cloud-upload': CloudUpload,
    upload: Upload,
    folder: Folder,
    'folder-open': FolderOpen,
    'arrow-left': ArrowLeft,
    'rotate-ccw': RotateCcw,
    'file-text': FileText,
    'log-out': LogOutIcon,
    lock: Lock,
    sun: Sun,
    moon: Moon,
    info: Info,
    bell: Bell,
    'chevron-right': ChevronRight,
    'refresh-cw': RefreshCcw,
    laptop: Laptop,
    monitor: Monitor,
    'chevron-down': ChevronDown,
    'chevron-up': ChevronUp,
    play: Play,
    delete: Trash,
    'chart-bar': ChartBar,
    database: Database,
    'trending-up': TrendingUp,
    image: Image,
    activity: Activity,
    file: File,
    package: Package,
    'file-plus': FilePlus,
    'external-link': ExternalLink,
    loader: Loader,
    pause: Pause,
    help: HelpCircle,
    shell: Shell,
  };

  getIcon() {
    const icon = this.iconMap[this.name()];
    if (!icon) {
      console.warn(`Icon "${this.name()}" not found in iconMap`);
      return Home; // Icono por defecto
    }
    return icon;
  }
}
